### ISSUE TITLE
Dinamically edit CS request SOAP

### ISSUE THREAD

**Issue by mathief123** [Argonne-National-Laboratory/node-red-contrib-ocpp#12]
Hello.

First of all, thank u for the amazing job you are doing.

Im trying to set an ocpp server using this library, so i would like to ask, is there a way to dinamically change the properties of the node so i don't have to make a node for each station that i wish to include? I already have saved every station on a mysql database so i can access to each ip.

Sorry in advice for my english, as its not my first languaje.

**Comment by bnystrom** [comment]
Hi,

Each Charge Point node sets up a websocket end route based on the Charge
Point "chargeBoxId", therefore there is currently no way to dynamically
assign a single CP node to multiple Charge Points.
I hope this answers your question.

Best Regards
Bryan Nystrom

**Comment by mathief123** [comment]
Hi.

So, in theory, i could just send the messaje at the websocket with the chargeBoxId and i woudn't need to send the messaje to each url specifically?

**Comment by bnystrom** [comment]
I'm sorry. Are you using the SOAP or JSON implementation?

A CS Request (SOAP) node needs to target a specific URL/IP since SOAP uses
a stateless connection. Either way, JSON or SOAP, there is no support for
dynamically sending messages to CPs by dynamically setting the CP endpoint.
If you want to form your own SOAP message packet and dynamically change the
chargebox in endpoint uri, that would be outside of our OCPP node-red
current ability.

Best Regards
Bryan Nystrom

**Comment by bnystrom** [comment]
Dynamic setting of CSMS/CS endpoint added to v1.3.0.
