### ISSUE TITLE
Not really an issue - where to specify the CP ip address or don't we need to?

### ISSUE THREAD

**Issue by tbryel** [Argonne-National-Laboratory/node-red-contrib-ocpp#18]
Hi,

I haven't any issue to report however i'm just not clear on the following things. I went through the documentation as well as the examples and object explanations multiple times but i'm just not able to get it. I own an Alfen NG9xx CP that i'm trying to connect with. It uses 1.6 OCPP-j so therefore I'm using the different JSON components as you also included in the example:

- I've specified the cbid (ChargeBoxId) to match the name that I had sent in my CP itself, but still I don't think this is enough to make a connection to my CP. Wouldn't the JSON CP also require an url/ip destination that it would try to connect with or can it really connect without knowing the CP IP address?
- The sample includes a 'HeartbeatInterval' request it also includes a 'GetConf response' function. This function seems to return a result for the 'HeartBeatInterval', I was expecting this would be returned by the actual CP instead. Is this function there just to demo a dummy scenario and wouldn't you need this function when you run 'real' scenarios or do we always need it and do we need to extend the function with any other getconfig or changeconfig parameters we want to pass?

I'm sorry for asking for these things, I just wasn't able to get my head around this eventhough it must be very straightforward for most people.

Kind regards,

Tim

**Comment by bnystrom** [comment]
Hi Tim,
OCPP 1.6J utilizes websockets. The EVSE (CP... your Alfen NG9xx) is always
the client in this setup. The client (your CP) needs to be configured to
connect to the Node-Red CS ip address. You will need to see if your CP/EVSE
OCPP software allows you to set that. CPs always establish the connection
to the CS.

The example shows sending a request to the "GetConfiguration" OCPP command
and asks for a "HeartbeatIntervals". The CP always/only responds back to
the main CS node. You'll have to catch the response coming back to that
node. There is only one websocket connection to each CP, and since the CP
initiates the connection to the CS, all communications go through it.

Best Regards
Bryan Nystrom

**Comment by tbryel** [comment]
Hi Bryan,

Thanks for the great response, I managed to setup my connection. I was aware I needed to set the CS in my Alfen Charger which I managed to do I just forgot to reboot my Alfen charger once I'd set it therefore it wasn't yet communicating anything to my CS, it required a reboot eventhough the log told me the settings were set/changed. 

I've really been trying to get my head around things and as I'm no expert in Javascript I was getting continous errors until i finally found that i shouldn't specify an integer value as a string and I had to remove "" around my integer value.

What I tried to achieve I managed to get done, i'm now able to invoke changeAvailability be setting the CP to 'Operative' or 'Inoperative'.

Really great stuff, thanks for the additional explanation Bryan this helped me get my head around it and give things another.

Kind regards,

Tim
